version: 0.0
os: linux
files:
   - source: /
     destination: /Workspace/Pipeline

hooks:
   BeforeInstall:
    - location: scripts/beforeinstall.sh
      runas: root
      timeout: 300
   AfterInstall:
    - location: scripts/afterinstall.sh
      runas: root
      timeout: 300