version: 0.0
os: linux
files:
   - source: /
     destination: /Workspace/Pipeline

hooks:
   BeforeInstall:
    - location: beforeinstall.sh
      runas: root
      timeout: 300
   ApplicationStart:
    - location: afterinstall.sh
      runas: root
      timeout: 300