version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Pipeline

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/appstart.sh
      runas: root
      timeout: 300