version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Nothing to install

  pre_build:
    commands:
      - npm install
       
  build:
    commands:
      - npm run build
  
  post_build:
    commands:
      - echo Nothing to post build
     

artifacts:
  files:
    - '**/*'
  base-directory: build